### ISSUE TITLE
Implement Algorithm for Clustering Multiple Cars

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/capstone_carcar5talk#17]
Due Date: 2015-04-08
skykhk01 with Hyesu

**Comment by Hyesu** [comment]
주변 차량 관리 및 클러스터링
Due Date: 05.25

**Comment by tnm1264** [comment]
서버에 접속할 수 있는 최대 디바이스의 개수를 정해놓는 것은 현재 구현되어 있습니다. DHCP 서버 설정에서 IP를 어디까지 할당할 것인지를 정해 놓았기 때문에 그렇게 볼 수 있는데요. 예를 들어 한 그룹에서 6개의 클라이언트만 관리하고 싶을 경우 192.168.10.1 ~ 192.168.10.6 으로 설정하면 그룹에서 6개의 디바이스만 관리하겠다는 뜻이 됩니다. 
클러스터링 문제는 ad-hoc 방식의 경우는 주변 각 파이와 개별로 통신을 하기 때문에 그룹을 지어줘야 하는 문제가 있었지만, ad-hoc 이 아닌 DHCP 방식의 경우, 한개의 서버가 이미 그룹을 생성하고 있기 때문에 따로 클러스터링이 필요할 것으로 보지는 않고 있습니다.
