### ISSUE TITLE
The Second Order

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/capstone_carcar5talk#30]
SD card(micro) for OS, file system : 5  
Battery for providing power to RPi  : 5  
RC car for Demo                             : 5

**Comment by parkhoon** [comment]
무선랜카드 추가주문 필요할거같습니다 5개

**Comment by Hyesu** [comment]
점퍼케이블 추가주문 필요합니다. mm, mf 둘 다 추가 주문 필요합니다.
