### ISSUE TITLE
The reason of using wireless lan

### ISSUE THREAD

**Issue by tnm1264** [Hyesu/capstone_carcar5talk#41]
왜 wlan을 선택했는지 구체적인 이유를 wiki 에 제시할 것

**Comment by Hyesu** [comment]
Due Date: 05.20 for 2차 중간 보고서서

**Comment by tnm1264** [comment]
Wlan 을 선택한 이유는 ad-hoc 방식을 이용할 경우, 다른 통신방법(블루투스 33m, DHCP 80m)보다 넓은 유효범위(wlan ad-hoc 120m)를 가지기 때문이고, 핸드폰의 wifi-direct를 이용하여 통신하기에는 wlan 이 더 간편하기 때문에 wlan을 선택하였습니다.
