### ISSUE TITLE
Send Byte Stream to Other Pi

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/capstone_carcar5talk#45]
Due Date: 05.17
완성 후 Hyesu에게 IPC 구현하라고 독촉해주세여!
네트워크 모듈 IPC는 이 부분 다음에 하는게 매끄러울 것 같슴다

**Comment by Hyesu** [comment]
Ad-hoc 연결이 안 된 경우, DHCP 방식으로 구현

**Comment by tnm1264** [comment]
Ad-hoc 의 경우는 EDIMAX 또는 Smart Phone의 Wifi-Direct로 구현할 것이고,
현재는 서버역할을 하는 Pi 와 클라이언트역할을 하는 Pi로 나누어 DHCP 를 통해서 라즈베리 파이간 통신을 구현 할 것입니다.
