### ISSUE TITLE
Network 연결 가능 범위 수치화

### ISSUE THREAD

**Issue by Hyesu** [Hyesu/capstone_carcar5talk#48]
Due Date: 05.20
가능하면 2차 보고 때까지 하면 좋고, 2차 보고 때 하더라도 최종 발표때까지 최적화 해야 할 것 같아여

**Comment by tnm1264** [comment]
Wlan ad-hoc : about 120m
Wlan DHCP : about 80m
Bluetooth : about 33m
실제 실험을 통해서 얻어온 결과입니다.
실험 방법은 두 파이가 서로 ping을 보내도록 설정한 후, 한 pi 는 제자리에 고정되어있고 다른 pi 를 이동시킨후 ping 이 끊어진 순간 고정된 pi와의 거리를 줄자로 측정하는 방식으로 실험하였습니다.
